spring.application.name=connectneon

# Conexión a Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-round-frog-ayph8eys.c-5.us-east-2.aws.neon.tech/escuelaDB?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_LXJK8tDSkCd6
# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver



# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Actuator    
# http://localhost:8080/actuator/mappings
# http://localhost:8080/swagger-ui/index.html
management.endpoints.web.exposure.include=*
